//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Reference { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<decimal> PreviousBalance { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
