//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public int PayeeID { get; set; }
        public int PayeeAccountID { get; set; }
        public int PayeeUserID { get; set; }
        public string PayeeReference { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
