//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToken
    {
        public int UserTokenID { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Used { get; set; }
    }
}
